[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=5
loglevel=info
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor_nginx_out.log
stderr_logfile=/var/log/supervisor_nginx_err.log

[program:sshd]
command=/usr/sbin/sshd -D -e
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor_sshd_out.log
stderr_logfile=/var/log/supervisor_sshd_err.log

[program:gost-ssh]
command=/usr/local/bin/gost -L="ws://127.0.0.1:8082?path=/ssh-ws-tunnel-core" -F="tcp://127.0.0.1:2222"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor_gost_out.log
stderr_logfile=/var/log/supervisor_gost_err.log

[program:xray-core]
command=/usr/local/bin/xray run -c /etc/tunnel_config/xray_ws.json
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor_xray_out.log
stderr_logfile=/var/log/supervisor_xray_err.log
